### ISSUE TITLE
Pin ruamel.yaml dependency version

### ISSUE THREAD

**Issue by hofbi** [jumanjihouse/pre-commit-hook-yamlfmt#47]
2 hours ago, a new version of https://pypi.org/project/ruamel.yaml/ was released, which introduced breaking changes. Ideally, if there is no update to this hook itself, there should be no changes in the transient dependencies. To prevent this in the future, I would suggest to either pin the version in the `setup.py` or switch to poetry where the version is pinned automatically in the `peotry.lock` file.

**Comment by resamaraschi** [comment]
Facing the same issue since this morning. In our case the issue comes up when using two hooks namely trailing-whitespace and yamlfmt. Somehow the get in each others way.

**Comment by hofbi** [comment]
An easy fix for this issue is to make use of the `additional_dependencies: [ruamel.yaml==0.17.21]`, but ideally this should be managed by yamlfmt itself

**Comment by jumanjiman** [comment]
👁️

**Comment by jumanjiman** [comment]
i'm pretty sure this is the culprit:

from https://sourceforge.net/p/ruamel-yaml/code/ci/0.17.22/tree/CHANGES

> plain scalars: put single words longer than width on a line of their own, instead
    of after the previous line (issue 427, reported by `Antoine Cotten 
    <https://sourceforge.net/u/antoineco/profile/>`_). Caveat: this currently results in a 
    space ending the previous line.

**temp** workaround: `additional_dependencies: [ruamel.yaml==0.17.21]`

**Comment by jumanjiman** [comment]
published new tag `0.2.3` to constrain ruamel.yaml version: 
https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/releases/tag/0.2.3
