### ISSUE TITLE
yamlfmt conflicts with yamllint if there is a long URL

### ISSUE THREAD

**Issue by poparotsy** [jumanjihouse/pre-commit-hook-yamlfmt#49]
- yamllint recommends breaking long URL [_more than 80 characters_] into a new line.
- yamlfmt removes the new line and put the URL back in one line.

**yamllint**
 error    line too long (86 > 80 characters)  (line-length)

**yamlfmt**
Format YAML files........................................................Failed
- hook id: yamlfmt
- files were modified by this hook

**Comment by jumanjiman** [comment]
👁️

**Comment by jumanjiman** [comment]
i'm pretty sure this is the culprit:

from https://sourceforge.net/p/ruamel-yaml/code/ci/0.17.22/tree/CHANGES

> plain scalars: put single words longer than width on a line of their own, instead
    of after the previous line (issue 427, reported by `Antoine Cotten 
    <https://sourceforge.net/u/antoineco/profile/>`_). Caveat: this currently results in a 
    space ending the previous line.

temp workaround: `additional_dependencies: [ruamel.yaml==0.17.21]`

**Comment by jumanjiman** [comment]
published new tag `0.2.3` to constrain ruamel.yaml version: 
https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/releases/tag/0.2.3
